gpu_id: ""
seed: 10000
display: True
im_size: 512
aligned: True

diffusion:
  target: models.script_util.create_gaussian_diffusion
  params:
    steps: 1000
    learn_sigma: True
    sigma_small: False
    noise_schedule: linear
    use_kl: False
    predict_xstart: False
    rescale_timesteps: False
    rescale_learned_sigmas: True
    timestep_respacing: "250"

model:
  target: models.unet.UNetModel
  #ckpt_path: E:/EC522-finalproject/ema0999_model_200000.pth
  ckpt_path: /projectnb/ec522/students/huatong/ema0999_model_200000.pth
  params:
    image_size: 512
    in_channels: 3
    model_channels: 32
    out_channels: 6
    attention_resolutions: [32, 16, 8]
    dropout: 0
    channel_mult: [1, 2, 4, 8, 8, 16, 16]
    num_res_blocks: [1, 2, 2, 2, 2, 3, 4]
    conv_resample: True
    dims: 2
    use_fp16: False
    num_head_channels: 64
    use_scale_shift_norm: True
    resblock_updown: False
    use_new_attention_order: False

model_ir:
  target: models.TurbulenceNet.TurbulenceNet
  ckpt_path: /projectnb/ec522/students/huatong/PiRN-main/assets/checkpoint/restoration_ckp_79.pth
  params:
    inp_channels: 3
    dim: 48
    num_blocks: [4, 6, 6, 8]
    heads: [1, 2, 4, 8]




